### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. 

### ISSUE THREAD

**Issue by yangqing-yq** [princeton-vl/CornerNet-Lite#9]
when run python demo.py, I met this question:
`python demo.py
total parameters: 116969339
loading from /home/qing/ngs/CornerNet-Lite/core/../cache/nnet/CornerNet_Saccade/CornerNet_Saccade_500000.pkl

Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    detector = CornerNet_Saccade()
  File "/home/qing/ngs/CornerNet-Lite/core/detectors.py", line 49, in __init__
    super(CornerNet_Saccade, self).__init__(coco, cornernet, cornernet_saccade_inference, model=model_path)
  File "/home/qing/ngs/CornerNet-Lite/core/base.py", line 14, in __init__
    self._nnet.load_pretrained_params(model)
  File "/home/qing/ngs/CornerNet-Lite/core/nnet/py_factory.py", line 123, in load_pretrained_params
    params = torch.load(f)
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 504, in persistent_load
    data_type(size), location)
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 113, in default_restore_location
    result = fn(storage, location)
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 94, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/qing/anaconda3/envs/CornerNet_Lite/lib/python3.7/site-packages/torch/serialization.py", line 78, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
`

CUDA Version 8.0.44

I have 4 Nvidia P40 GPUs

**Comment by Yunski** [comment]
Hi, Thanks for trying out CornerNet-Lite! Were you able to resolve this? 
Note that the code in this repo as-is requires CUDA 10. Perhaps you can check if your conda environment contains the correct PyTorch installation for your local setup. Otherwise, upgrading your CUDA should resolve this.
Yun

**Comment by zhangli-0812** [comment]
I met the same problem. Have you solved it? My CUDA is 10.0.

**Comment by yghcats** [comment]
@yangqing-yq 
Hi，how do you solve this problem?? I made this mistake, too.
Thank you!

**Comment by yangqing-yq** [comment]
> I met the same problem. Have you solved it? My CUDA is 10.0.

@yghcats @Tension001 Sorry, My CUDA is 9.2, I still not try 10.0 version yet. I will let you know my result as soon as I tried it out.

**Comment by yghcats** [comment]
@yangqing-yq 
I have a problem with the driver to correct it.
Thank you

**Comment by zhangli-0812** [comment]
I have solved this problem by upgrading my NVIDIA driver. My former driver is 384, which does not match CUDA 10.0. CUDA 10.0 needs 410 or 418.

**Comment by KeeaattJj** [comment]
my cuda is  CUDA Version 8.0.61 .solve this problem by using pytorch 1.0.0  py3.7_cuda9.0.176_cudnn7.4.1_1

**Comment by jg925** [comment]
@KeeaattJj Does this mean there is a way to get around needing CUDA 10?
